# 🚀 GPT

In this notebook, we'll walk through the steps required to train your own GPT model on the wine review dataset

The code is adapted from the excellent [GPT tutorial](https://keras.io/examples/generative/text_generation_with_miniature_gpt/) created by Apoorv Nandan available on the Keras website.

In [10]:
%load_ext autoreload
%autoreload 2
import numpy as np
import json
import re
import string
from IPython.display import display, HTML

import tensorflow as tf
from tensorflow.keras import layers, models, losses, callbacks

## 0. Parameters <a name="parameters"></a>

In [11]:
VOCAB_SIZE = 10000
MAX_LEN = 80
EMBEDDING_DIM = 256
KEY_DIM = 256
N_HEADS = 2
FEED_FORWARD_DIM = 256
VALIDATION_SPLIT = 0.2
SEED = 42
LOAD_MODEL = False
BATCH_SIZE = 32
EPOCHS = 5

## 1. Load the data <a name="load"></a>

In [14]:
with open("/app/data/wine-reviews/winemag-data-130k-v2.json", encoding="utf-8", errors="ignore") as json_data:
    wine_data = json.load(json_data)


In [15]:
wine_data[10]

{'points': '87',
 'title': 'Kirkland Signature 2011 Mountain Cuvée Cabernet Sauvignon (Napa Valley)',
 'description': 'Soft, supple plum envelopes an oaky structure in this Cabernet, supported by 15% Merlot. Coffee and chocolate complete the picture, finishing strong at the end, resulting in a value-priced wine of attractive flavor and immediate accessibility.',
 'taster_name': 'Virginie Boone',
 'taster_twitter_handle': '@vboone',
 'price': 19,
 'designation': 'Mountain Cuvée',
 'variety': 'Cabernet Sauvignon',
 'region_1': 'Napa Valley',
 'region_2': 'Napa',
 'province': 'California',
 'country': 'US',
 'winery': 'Kirkland Signature'}

In [16]:
# Filter the dataset
filtered_data = [
    "wine review : "
    + x["country"]
    + " : "
    + x["province"]
    + " : "
    + x["variety"]
    + " : "
    + x["description"]
    for x in wine_data
    if x["country"] is not None
    and x["province"] is not None
    and x["variety"] is not None
    and x["description"] is not None
]

In [17]:
# Count the recipes
n_wines = len(filtered_data)
print(f"{n_wines} recipes loaded")

129907 recipes loaded


In [18]:
example = filtered_data[25]
print(example)

wine review : US : California : Pinot Noir : Oak and earth intermingle around robust aromas of wet forest floor in this vineyard-designated Pinot that hails from a high-elevation site. Small in production, it offers intense, full-bodied raspberry and blackberry steeped in smoky spice and smooth texture.


## 2. Tokenize the data <a name="tokenize"></a>

In [19]:
# Pad the punctuation, to treat them as separate 'words'
def pad_punctuation(s):
    s = re.sub(f"([{string.punctuation}, '\n'])", r" \1 ", s)
    s = re.sub(" +", " ", s)
    return s


text_data = [pad_punctuation(x) for x in filtered_data]

In [20]:
# Display an example of a recipe
example_data = text_data[25]
example_data

'wine review : US : California : Pinot Noir : Oak and earth intermingle around robust aromas of wet forest floor in this vineyard - designated Pinot that hails from a high - elevation site . Small in production , it offers intense , full - bodied raspberry and blackberry steeped in smoky spice and smooth texture . '

In [21]:
# Convert to a Tensorflow Dataset
text_ds = (
    tf.data.Dataset.from_tensor_slices(text_data)
    .batch(BATCH_SIZE)
    .shuffle(1000)
)

2024-08-31 09:15:13.840788: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-08-31 09:15:13.858826: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-08-31 09:15:13.859147: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-08-31 09:15:13.869522: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate

In [22]:
# Create a vectorisation layer
vectorize_layer = layers.TextVectorization(
    standardize="lower",
    max_tokens=VOCAB_SIZE,
    output_mode="int",
    output_sequence_length=MAX_LEN + 1,
)

In [23]:
# Adapt the layer to the training set
vectorize_layer.adapt(text_ds)
vocab = vectorize_layer.get_vocabulary()

In [24]:
# Display some token:word mappings
for i, word in enumerate(vocab[:10]):
    print(f"{i}: {word}")

0: 
1: [UNK]
2: :
3: ,
4: .
5: and
6: the
7: wine
8: a
9: of


In [25]:
# Display the same example converted to ints
example_tokenised = vectorize_layer(example_data)
print(example_tokenised.numpy())

[   7   10    2   20    2   29    2   43   62    2   55    5  243 4145
  453  634   26    9  497  499  667   17   12  142   14 2214   43   25
 2484   32    8  223   14 2213  948    4  594   17  987    3   15   75
  237    3   64   14   82   97    5   74 2633   17  198   49    5  125
   77    4    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0]


## 3. Create the Training Set <a name="create"></a>

In [26]:
# Create the training set of recipes and the same text shifted by one word
def prepare_inputs(text):
    text = tf.expand_dims(text, -1)
    tokenized_sentences = vectorize_layer(text)
    x = tokenized_sentences[:, :-1]
    y = tokenized_sentences[:, 1:]
    return x, y


train_ds = text_ds.map(prepare_inputs)

In [27]:
example_input_output = train_ds.take(1).get_single_element()

In [28]:
# Example Input
example_input_output[0][0]

<tf.Tensor: shape=(80,), dtype=int64, numpy=
array([   7,   10,    2,   20,    2,   29,    2,   45,   44,    2, 1151,
         14,   78,   17,  216,    3,   12,  756,    7,   75,    8, 2511,
        141,   23,    6,   60,    3,  318,   47,    8,  564, 2257,    9,
       1106,    5, 2410,    4,  661,  543,    5, 1078,    3,   15,  253,
       5898,  140,    5,   58,    4,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0])>

In [29]:
# Example Output (shifted by one token)
example_input_output[1][0]

<tf.Tensor: shape=(80,), dtype=int64, numpy=
array([  10,    2,   20,    2,   29,    2,   45,   44,    2, 1151,   14,
         78,   17,  216,    3,   12,  756,    7,   75,    8, 2511,  141,
         23,    6,   60,    3,  318,   47,    8,  564, 2257,    9, 1106,
          5, 2410,    4,  661,  543,    5, 1078,    3,   15,  253, 5898,
        140,    5,   58,    4,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0])>

## 5. Create the causal attention mask function <a name="causal"></a>

In [30]:
def causal_attention_mask(batch_size, n_dest, n_src, dtype):
    i = tf.range(n_dest)[:, None]
    j = tf.range(n_src)
    m = i >= j - n_src + n_dest
    mask = tf.cast(m, dtype)
    mask = tf.reshape(mask, [1, n_dest, n_src])
    mult = tf.concat(
        [tf.expand_dims(batch_size, -1), tf.constant([1, 1], dtype=tf.int32)], 0
    )
    return tf.tile(mask, mult)


np.transpose(causal_attention_mask(1, 10, 10, dtype=tf.int32)[0])

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int32)

## 6. Create a Transformer Block layer <a name="transformer"></a>

In [31]:
class TransformerBlock(layers.Layer):
    def __init__(self, num_heads, key_dim, embed_dim, ff_dim, dropout_rate=0.1):
        super(TransformerBlock, self).__init__()
        self.num_heads = num_heads
        self.key_dim = key_dim
        self.embed_dim = embed_dim
        self.ff_dim = ff_dim
        self.dropout_rate = dropout_rate
        self.attn = layers.MultiHeadAttention(
            num_heads, key_dim, output_shape=embed_dim
        )
        self.dropout_1 = layers.Dropout(self.dropout_rate)
        self.ln_1 = layers.LayerNormalization(epsilon=1e-6)
        self.ffn_1 = layers.Dense(self.ff_dim, activation="relu")
        self.ffn_2 = layers.Dense(self.embed_dim)
        self.dropout_2 = layers.Dropout(self.dropout_rate)
        self.ln_2 = layers.LayerNormalization(epsilon=1e-6)

    def call(self, inputs):
        input_shape = tf.shape(inputs)
        batch_size = input_shape[0]
        seq_len = input_shape[1]
        causal_mask = causal_attention_mask(
            batch_size, seq_len, seq_len, tf.bool
        )
        attention_output, attention_scores = self.attn(
            inputs,
            inputs,
            attention_mask=causal_mask,
            return_attention_scores=True,
        )
        attention_output = self.dropout_1(attention_output)
        out1 = self.ln_1(inputs + attention_output)
        ffn_1 = self.ffn_1(out1)
        ffn_2 = self.ffn_2(ffn_1)
        ffn_output = self.dropout_2(ffn_2)
        return (self.ln_2(out1 + ffn_output), attention_scores)

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "key_dim": self.key_dim,
                "embed_dim": self.embed_dim,
                "num_heads": self.num_heads,
                "ff_dim": self.ff_dim,
                "dropout_rate": self.dropout_rate,
            }
        )
        return config

## 7. Create the Token and Position Embedding <a name="embedder"></a>

In [32]:
class TokenAndPositionEmbedding(layers.Layer):
    def __init__(self, max_len, vocab_size, embed_dim):
        super(TokenAndPositionEmbedding, self).__init__()
        self.max_len = max_len
        self.vocab_size = vocab_size
        self.embed_dim = embed_dim
        self.token_emb = layers.Embedding(
            input_dim=vocab_size, output_dim=embed_dim
        )
        self.pos_emb = layers.Embedding(input_dim=max_len, output_dim=embed_dim)

    def call(self, x):
        maxlen = tf.shape(x)[-1]
        positions = tf.range(start=0, limit=maxlen, delta=1)
        positions = self.pos_emb(positions)
        x = self.token_emb(x)
        return x + positions

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "max_len": self.max_len,
                "vocab_size": self.vocab_size,
                "embed_dim": self.embed_dim,
            }
        )
        return config

## 8. Build the Transformer model <a name="transformer_decoder"></a>

In [33]:
inputs = layers.Input(shape=(None,), dtype=tf.int32)
x = TokenAndPositionEmbedding(MAX_LEN, VOCAB_SIZE, EMBEDDING_DIM)(inputs)
x, attention_scores = TransformerBlock(
    N_HEADS, KEY_DIM, EMBEDDING_DIM, FEED_FORWARD_DIM
)(x)
outputs = layers.Dense(VOCAB_SIZE, activation="softmax")(x)
gpt = models.Model(inputs=inputs, outputs=[outputs, attention_scores])
gpt.compile("adam", loss=[losses.SparseCategoricalCrossentropy(), None])

In [34]:
gpt.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, None)]            0         
                                                                 
 token_and_position_embeddin  (None, None, 256)        2580480   
 g (TokenAndPositionEmbeddin                                     
 g)                                                              
                                                                 
 transformer_block (Transfor  ((None, None, 256),      658688    
 merBlock)                    (None, 2, None, None))             
                                                                 
 dense_2 (Dense)             (None, None, 10000)       2570000   
                                                                 
Total params: 5,809,168
Trainable params: 5,809,168
Non-trainable params: 0
___________________________________________________

In [35]:
if LOAD_MODEL:
    # model.load_weights('./models/model')
    gpt = models.load_model("./models/gpt", compile=True)

## 9. Train the Transformer <a name="train"></a>

In [36]:
# Create a TextGenerator checkpoint
class TextGenerator(callbacks.Callback):
    def __init__(self, index_to_word, top_k=10):
        self.index_to_word = index_to_word
        self.word_to_index = {
            word: index for index, word in enumerate(index_to_word)
        }

    def sample_from(self, probs, temperature):
        probs = probs ** (1 / temperature)
        probs = probs / np.sum(probs)
        return np.random.choice(len(probs), p=probs), probs

    def generate(self, start_prompt, max_tokens, temperature):
        start_tokens = [
            self.word_to_index.get(x, 1) for x in start_prompt.split()
        ]
        sample_token = None
        info = []
        while len(start_tokens) < max_tokens and sample_token != 0:
            x = np.array([start_tokens])
            y, att = self.model.predict(x, verbose=0)
            sample_token, probs = self.sample_from(y[0][-1], temperature)
            info.append(
                {
                    "prompt": start_prompt,
                    "word_probs": probs,
                    "atts": att[0, :, -1, :],
                }
            )
            start_tokens.append(sample_token)
            start_prompt = start_prompt + " " + self.index_to_word[sample_token]
        print(f"\ngenerated text:\n{start_prompt}\n")
        return info

    def on_epoch_end(self, epoch, logs=None):
        self.generate("wine review", max_tokens=80, temperature=1.0)

In [37]:
# Create a model save checkpoint
model_checkpoint_callback = callbacks.ModelCheckpoint(
    filepath="./checkpoint/checkpoint.ckpt",
    save_weights_only=True,
    save_freq="epoch",
    verbose=0,
)

tensorboard_callback = callbacks.TensorBoard(log_dir="./logs")

# Tokenize starting prompt
text_generator = TextGenerator(vocab)

In [38]:
gpt.fit(
    train_ds,
    epochs=EPOCHS,
    callbacks=[model_checkpoint_callback, tensorboard_callback, text_generator],
)

Epoch 1/5
4060/4060 [==============================] - ETA: 0s - loss: 2.2540 - dense_2_loss: 2.2540
generated text:
wine review : spain : northern spain : tempranillo : a nice things tinged with animal hide , dark - fruit aromas , milk chocolate and [UNK] set up the palate . this feels flush , acidic , with deep ; nothing can be one remember . blackberry and cassis flavors show through the finish . 

4060/4060 [==============================] - 359s 88ms/step - loss: 2.2540 - dense_2_loss: 2.2540
Epoch 2/5
4060/4060 [==============================] - ETA: 0s - loss: 1.9583 - dense_2_loss: 1.9583
generated text:
wine review : us : california : zinfandel : never too brittle . it ' s kind of acidity , and even housed in [UNK] , with raspberries , black pepper , currants and spice . the wine is full bodied , chewy and juicy in flavor , but could use longer . 

4060/4060 [==============================] - 355s 88ms/step - loss: 1.9583 - dense_2_loss: 1.9583
Epoch 3/5
4060/4060 [===========

In [39]:
# Save the final model
gpt.save("./models/gpt")

INFO:tensorflow:Assets written to: ./models/gpt/assets


INFO:tensorflow:Assets written to: ./models/gpt/assets


# 3. Generate text using the Transformer

In [40]:
def print_probs(info, vocab, top_k=5):
    for i in info:
        highlighted_text = []
        for word, att_score in zip(
            i["prompt"].split(), np.mean(i["atts"], axis=0)
        ):
            highlighted_text.append(
                '<span style="background-color:rgba(135,206,250,'
                + str(att_score / max(np.mean(i["atts"], axis=0)))
                + ');">'
                + word
                + "</span>"
            )
        highlighted_text = " ".join(highlighted_text)
        display(HTML(highlighted_text))

        word_probs = i["word_probs"]
        p_sorted = np.sort(word_probs)[::-1][:top_k]
        i_sorted = np.argsort(word_probs)[::-1][:top_k]
        for p, i in zip(p_sorted, i_sorted):
            print(f"{vocab[i]}:   \t{np.round(100*p,2)}%")
        print("--------\n")

In [41]:
info = text_generator.generate(
    "wine review : us", max_tokens=80, temperature=1.0
)


generated text:
wine review : us : oregon : pinot noir : [UNK] crew rabbit ranch sources for the craft this crisp , fresh but disappointing in proportion . a bit of vineyards in this brings a good persistence of cherry . it could benefit from additional bottle age for another decade . 



In [42]:
info = text_generator.generate(
    "wine review : italy", max_tokens=80, temperature=0.5
)


generated text:
wine review : italy : tuscany : red blend : a blend of cabernet sauvignon and merlot , this offers a fine bouquet of blue flowers , leather , tobacco , black olive and spice . the palate is rich and full bodied , with a polished texture and a long , lingering finish . 



In [43]:
info = text_generator.generate(
    "wine review : germany", max_tokens=80, temperature=0.5
)
print_probs(info, vocab)


generated text:
wine review : germany : mosel : riesling : whiffs of smoke and slate lend a savory tone to pressed apple and pineapple in this dry , off - dry riesling . it ' s juicy in tangerine and lime acidity , finishing with a brisk , fresh finish . 



::   	100.0%
grosso:   	0.0%
zealand:   	0.0%
-:   	0.0%
africa:   	0.0%
--------



mosel:   	84.67%
rheingau:   	7.81%
rheinhessen:   	6.66%
nahe:   	0.48%
pfalz:   	0.27%
--------



::   	99.99%
-:   	0.01%
grosso:   	0.0%
blanc:   	0.0%
valley:   	0.0%
--------



riesling:   	99.87%
spätburgunder:   	0.04%
weissburgunder:   	0.04%
pinot:   	0.01%
sparkling:   	0.01%
--------



::   	100.0%
-:   	0.0%
blanc:   	0.0%
grosso:   	0.0%
blend:   	0.0%
--------



a:   	46.16%
whiffs:   	11.16%
dusty:   	6.34%
smoke:   	4.36%
the:   	3.97%
--------



of:   	100.0%
suggesting:   	0.0%
and:   	0.0%
like:   	0.0%
recall:   	0.0%
--------



smoke:   	90.14%
crushed:   	1.64%
saffron:   	1.56%
lanolin:   	1.53%
slate:   	1.39%
--------



and:   	98.23%
,:   	1.69%
lend:   	0.07%
accent:   	0.01%
add:   	0.0%
--------



crushed:   	26.76%
earth:   	22.66%
slate:   	21.44%
smoke:   	14.55%
bramble:   	2.38%
--------



lend:   	95.81%
add:   	3.43%
extend:   	0.45%
are:   	0.11%
accent:   	0.07%
--------



a:   	84.63%
complexity:   	8.53%
an:   	2.3%
savory:   	1.87%
nuance:   	0.78%
--------



savory:   	98.44%
fresh:   	0.19%
dusty:   	0.15%
delicate:   	0.15%
sultry:   	0.13%
--------



tone:   	96.93%
,:   	1.62%
complexity:   	0.6%
edge:   	0.32%
savory:   	0.09%
--------



to:   	99.99%
in:   	0.01%
on:   	0.0%
.:   	0.0%
and:   	0.0%
--------



pressed:   	58.89%
this:   	21.32%
ripe:   	7.65%
fresh:   	4.63%
preserved:   	3.44%
--------



apple:   	86.18%
yellow:   	9.19%
apples:   	4.36%
peach:   	0.05%
white:   	0.04%
--------



and:   	98.41%
,:   	1.06%
in:   	0.47%
on:   	0.02%
-:   	0.02%
--------



pear:   	87.31%
lemon:   	5.12%
tangerine:   	3.03%
peach:   	2.15%
grapefruit:   	0.89%
--------



in:   	93.15%
flavors:   	4.39%
on:   	1.82%
notes:   	0.48%
tones:   	0.04%
--------



this:   	100.0%
the:   	0.0%
a:   	0.0%
an:   	0.0%
core:   	0.0%
--------



dry:   	46.41%
off:   	21.27%
intensely:   	9.24%
gorgeously:   	3.25%
bristling:   	1.7%
--------



,:   	99.12%
riesling:   	0.59%
yet:   	0.15%
wine:   	0.04%
spätlese:   	0.03%
--------



delicately:   	25.26%
intensely:   	16.28%
off:   	11.8%
crisp:   	6.67%
elegantly:   	5.47%
--------



-:   	100.0%
dry:   	0.0%
by:   	0.0%
of:   	0.0%
and:   	0.0%
--------



dry:   	100.0%
[UNK]:   	0.0%
sweet:   	0.0%
savory:   	0.0%
to:   	0.0%
--------



riesling:   	99.19%
spätlese:   	0.37%
wine:   	0.27%
kabinett:   	0.1%
style:   	0.02%
--------



.:   	99.85%
,:   	0.09%
full:   	0.04%
that:   	0.01%
from:   	0.01%
--------



it:   	91.1%
the:   	6.42%
zesty:   	0.57%
while:   	0.34%
a:   	0.27%
--------



':   	100.0%
has:   	0.0%
is:   	0.0%
finishes:   	0.0%
drinks:   	0.0%
--------



s:   	100.0%
ll:   	0.0%
t:   	0.0%
kabinett:   	0.0%
[UNK]:   	0.0%
--------



a:   	71.95%
refreshingly:   	8.91%
medium:   	4.76%
crisp:   	1.36%
rich:   	1.28%
--------



and:   	37.04%
in:   	29.9%
,:   	17.01%
on:   	11.82%
with:   	3.97%
--------



acidity:   	71.09%
tangerine:   	5.54%
grapefruit:   	4.14%
fruit:   	3.96%
peach:   	3.51%
--------



and:   	87.17%
,:   	10.56%
acidity:   	1.64%
in:   	0.36%
-:   	0.13%
--------



lime:   	51.37%
grapefruit:   	18.07%
peach:   	11.4%
tangerine:   	9.42%
lemon:   	5.37%
--------



acidity:   	36.56%
flavors:   	23.54%
in:   	17.49%
on:   	11.74%
-:   	6.93%
--------



,:   	93.1%
.:   	4.5%
that:   	1.22%
on:   	0.73%
and:   	0.31%
--------



with:   	83.5%
but:   	4.73%
finishing:   	4.59%
and:   	3.87%
yet:   	1.68%
--------



on:   	45.1%
with:   	30.32%
long:   	6.54%
brisk:   	5.77%
a:   	3.32%
--------



a:   	99.7%
an:   	0.13%
fresh:   	0.04%
hints:   	0.03%
some:   	0.02%
--------



reverberating:   	12.29%
murmur:   	9.38%
steely:   	8.85%
long:   	6.91%
fresh:   	6.82%
--------



,:   	84.14%
lime:   	5.39%
lemon:   	3.62%
edge:   	1.82%
lift:   	1.42%
--------



clean:   	29.85%
refreshing:   	16.86%
steely:   	11.56%
cutting:   	11.51%
lemony:   	11.31%
--------



,:   	28.98%
feel:   	12.77%
lime:   	9.32%
aftertaste:   	9.14%
acidity:   	6.29%
--------



.:   	99.99%
that:   	0.0%
,:   	0.0%
of:   	0.0%
and:   	0.0%
--------



:   	70.39%
drink:   	29.32%
drinks:   	0.17%
it:   	0.06%
enjoy:   	0.05%
--------

